using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Rsp.Portal.Application.Constants;
using Rsp.Portal.Application.DTOs.CmsQuestionset;
using Rsp.Portal.Application.DTOs.CmsQuestionset.Modifications;
using Rsp.Portal.Application.DTOs.Requests;
using Rsp.Portal.Application.DTOs.Responses;
using Rsp.Portal.Application.Responses;
using Rsp.Portal.Application.Services;
using Rsp.Portal.Web.Features.Modifications;
using Rsp.Portal.Web.Features.Modifications.Models;
using Rsp.Portal.Web.Models;

namespace Rsp.Portal.UnitTests.Web.Features.Modifications.ModificationDetailsControllerTests;

public class ModificationDetails_Success : TestServiceBase<ModificationDetailsController>
{
    [Fact]
    public async Task Returns_View_With_Mapped_Changes_And_Flags()
    {
        // Arrange
        var http = new DefaultHttpContext();
        Sut.ControllerContext = new() { HttpContext = http };
        Sut.TempData = new TempDataDictionary(http, Mock.Of<ITempDataProvider>());

        var modId = Guid.NewGuid();
        var changeId = Guid.NewGuid();

        // 1. GetModification -> one modification entry
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModification("PR1", It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<ProjectModificationResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new ProjectModificationResponse
                {
                    Id = modId,
                    ModificationIdentifier = modId.ToString(),
                    Status = ModificationStatus.InDraft,
                    ProjectRecordId = "PR1",
                    ModificationNumber = 1,
                    CreatedDate = DateTime.UtcNow,
                    UpdatedDate = DateTime.UtcNow,
                    CreatedBy = "TestUser",
                    UpdatedBy = "TestUser",
                    ModificationType = "Substantial",
                    Category = "Category A",
                    ReviewType = "Full Review"
                }
            });

        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationReviewResponses("PR1", It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<ProjectModificationReviewResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new ProjectModificationReviewResponse
                {
                    ModificationId = modId,
                    RequestForInformationReasons = []
                }
            });

        // 2. GetModificationChanges -> one change
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChanges(It.IsAny<string>(), It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<IEnumerable<ProjectModificationChangeResponse>>
            {
                StatusCode = HttpStatusCode.OK,
                Content = [new() { Id = changeId, SpecificAreaOfChange = "SA1", AreaOfChange = "A1", Status = ModificationStatus.InDraft }]
            });

        // 3. GetInitialModificationQuestions -> resolve names
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetInitialModificationQuestions())
            .ReturnsAsync(new ServiceResponse<StartingQuestionsDto>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new StartingQuestionsDto
                {
                    AreasOfChange =
                    [
                        new()
                        {
                            AutoGeneratedId = "A1",
                            OptionName = "Area Name",
                            SpecificAreasOfChange = [ new() { AutoGeneratedId = "SA1", OptionName = "Specific Name" } ]
                        }
                    ]
                }
            });

        // 4. For UpdateModificationChanges flow we need journey questions and answers per change call; set validator minimal
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationsJourney("SA1"))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new CmsQuestionSetResponse
                {
                    Sections = [new SectionModel { Id = "S1", CategoryId = "C1", Questions = [new QuestionModel { Id = "Q1", QuestionId = "Q1", Name = "Q1", AnswerDataType = "Text", CategoryId = "C1", Conformance = "Mandatory" }] }]
                }
            });

        Mocker
            .GetMock<IRespondentService>()
            .Setup(s => s.GetModificationChangeAnswers(changeId, It.IsAny<string>()))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>> { StatusCode = HttpStatusCode.OK, Content = [] });

        var answers = new List<RespondentAnswerDto>
            {
                new() { QuestionId = QuestionIds.ShortProjectTitle, AnswerText = "Project X" },
                new() { QuestionId = QuestionIds.ProjectPlannedEndDate, AnswerText = "01/01/2025" }
            };
        Mocker
            .GetMock<IRespondentService>()
            .Setup(s => s.GetRespondentAnswers(It.IsAny<string>(), QuestionCategories.ProjectRecord))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>> { StatusCode = HttpStatusCode.OK, Content = answers });

        // Use a permissive validator that sets IsValid true
        Mocker
            .GetMock<IValidator<QuestionnaireViewModel>>()
            .Setup(v => v.ValidateAsync(It.IsAny<ValidationContext<QuestionnaireViewModel>>(), default))
            .ReturnsAsync(new FluentValidation.Results.ValidationResult());

        // Mock RankingOfChange response to avoid NullReferenceException
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationRanking(It.IsAny<RankingOfChangeRequest>()))
            .ReturnsAsync(new ServiceResponse<RankingOfChangeResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new RankingOfChangeResponse
                {
                    ModificationType = new() { Substantiality = "Substantial", Order = 1 },
                    Categorisation = new() { Category = "Category", Order = 1 },
                    ReviewType = "ReviewType"
                }
            });

        // Act
        var result = await Sut.ModificationDetails("PR1", "IRAS", "Short", modId);

        // Assert
        var view = result.ShouldBeOfType<ViewResult>();
        var model = view.Model.ShouldBeOfType<ModificationDetailsViewModel>();

        model.ModificationId.ShouldBe(modId.ToString());
        model.ModificationChanges.Count.ShouldBe(1);
        model.ModificationChanges[0].AreaOfChangeName.ShouldBe("Area Name");
        model.ModificationChanges[0].SpecificChangeName.ShouldBe("Specific Name");
    }

    [Fact]
    public async Task ModificationDetails_Returns_View_Without_SponsorDetails_When_NotSponsorRevision()
    {
        // Arrange
        var http = new DefaultHttpContext();
        Sut.ControllerContext = new() { HttpContext = http };
        Sut.TempData = new TempDataDictionary(http, Mock.Of<ITempDataProvider>());

        var modId = Guid.NewGuid();
        var changeId = Guid.NewGuid();

        // modification
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModification("PR1", modId))
            .ReturnsAsync(new ServiceResponse<ProjectModificationResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Id = modId,
                    ModificationIdentifier = modId.ToString(),
                    ProjectRecordId = "PR1",
                    Status = ModificationStatus.InDraft
                }
            });

        // changes
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChanges("PR1", modId))
            .ReturnsAsync(new ServiceResponse<IEnumerable<ProjectModificationChangeResponse>>
            {
                StatusCode = HttpStatusCode.OK,
                Content =
                [
                    new() { Id = changeId, AreaOfChange = "A1", SpecificAreaOfChange = "SA1" }
                ]
            });

        // initial questions
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetInitialModificationQuestions())
            .ReturnsAsync(new ServiceResponse<StartingQuestionsDto>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    AreasOfChange =
                    [
                        new()
                    {
                        AutoGeneratedId = "A1",
                        OptionName = "Area Name",
                        SpecificAreasOfChange =
                        [
                            new() { AutoGeneratedId = "SA1", OptionName = "Specific Name" }
                        ]
                    }
                    ]
                }
            });

        // change journey
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationsJourney("SA1"))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Sections =
                    [
                        new()
                    {
                        Id = "S1",
                        CategoryId = "C1",
                        Questions =
                        [
                            new QuestionModel
                            {
                                Id = "Q1",
                                QuestionId = "Q1",
                                AnswerDataType = "Text",
                                CategoryId = "C1"
                            }
                        ]
                    }
                    ]
                }
            });

        Mocker.GetMock<IRespondentService>()
            .Setup(s => s.GetModificationChangeAnswers(changeId, "PR1"))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>>
            {
                StatusCode = HttpStatusCode.OK,
                Content = []
            });

        // ranking
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationRanking(It.IsAny<RankingOfChangeRequest>()))
            .ReturnsAsync(new ServiceResponse<RankingOfChangeResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    ModificationType = new() { Substantiality = "None", Order = 1 },
                    Categorisation = new() { Category = "Cat", Order = 1 }
                }
            });

        Mocker.GetMock<IValidator<QuestionnaireViewModel>>()
            .Setup(v => v.ValidateAsync(It.IsAny<ValidationContext<QuestionnaireViewModel>>(), default))
            .ReturnsAsync(new ValidationResult());

        // Act
        var result = await Sut.ModificationDetails("PR1", "IRAS", "Short", modId);

        // Assert
        var view = result.ShouldBeOfType<ViewResult>();
        var model = view.Model.ShouldBeOfType<ModificationDetailsViewModel>();

        model.ModificationChanges.Count.ShouldBe(1);
        model.SponsorDetails.ShouldBeEmpty();
    }

    [Fact]
    public async Task ModificationDetails_Executes_SponsorRevisionFlow()
    {
        // Arrange
        var http = new DefaultHttpContext();
        Sut.ControllerContext = new() { HttpContext = http };
        Sut.TempData = new TempDataDictionary(http, Mock.Of<ITempDataProvider>());

        var modId = Guid.NewGuid();
        var changeId = Guid.NewGuid();

        var sponsorUserId = Guid.NewGuid();
        var rtsId = "RTS-123";

        // main modification with ReviseAndAuthorise
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModification("PR1", modId))
            .ReturnsAsync(new ServiceResponse<ProjectModificationResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Id = modId,
                    ModificationIdentifier = modId.ToString(),
                    ProjectRecordId = "PR1",
                    Status = ModificationStatus.ReviseAndAuthorise
                }
            });

        // changes
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChanges("PR1", modId))
            .ReturnsAsync(new ServiceResponse<IEnumerable<ProjectModificationChangeResponse>>
            {
                StatusCode = HttpStatusCode.OK,
                Content =
                [
                    new() { Id = changeId, AreaOfChange = "A1", SpecificAreaOfChange = "SA1" }
                ]
            });

        // initial questions
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetInitialModificationQuestions())
            .ReturnsAsync(new ServiceResponse<StartingQuestionsDto>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    AreasOfChange =
                    [
                        new()
                    {
                        AutoGeneratedId = "A1",
                        OptionName = "Area Name",
                        SpecificAreasOfChange =
                        [
                            new() { AutoGeneratedId = "SA1", OptionName = "Specific Name" }
                        ]
                    }
                    ]
                }
            });

        // journey for update changes
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationsJourney("SA1"))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Sections =
                    [
                        new()
                    {
                        Id = "S1",
                        CategoryId = "C1",
                        Questions =
                        [
                            new QuestionModel
                            {
                                Id = "Q1",
                                QuestionId = "Q1",
                                AnswerDataType = "Text",
                                CategoryId = "C1"
                            }
                        ]
                    }
                    ]
                }
            });

        Mocker.GetMock<IRespondentService>()
            .Setup(s => s.GetModificationChangeAnswers(changeId, "PR1"))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>>
            {
                StatusCode = HttpStatusCode.OK,
                Content = []
            });

        // ============================================
        // SPONSOR BLOCK MOCKS
        // ============================================

        // SponsorDetails questionset
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationQuestionSet(
                It.Is<string>(x => x == "pm-sponsor-reference"),
                It.IsAny<string?>()))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Sections =
                    [
                        new()
                    {
                        Id = "SP1",
                        CategoryId = "SPC",
                        Questions =
                        [
                            new QuestionModel
                            {
                                Id = "SPQ1",
                                QuestionId = "SPQ1",
                                AnswerDataType = "Text",
                                CategoryId = "SPC"
                            }
                        ]
                    }
                    ]
                }
            });

        // Sponsor answers
        Mocker.GetMock<IRespondentService>()
            .Setup(s => s.GetModificationAnswers(modId, "PR1"))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>>
            {
                StatusCode = HttpStatusCode.OK,
                Content = [new() { QuestionId = "SPQ1", AnswerText = "SponsorAnswer" }]
            });

        // DocumentDetails question set
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationQuestionSet(
                It.Is<string>(x => x == "pdm-document-metadata"),
                It.IsAny<string?>()))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    Sections =
                    [
                        new()
                    {
                        Id = "DOC1",
                        CategoryId = "D1",
                        Questions =
                        [
                            new QuestionModel
                            {
                                Id = "DocType",
                                QuestionId = ModificationQuestionIds.DocumentType,
                                AnswerDataType = "Text",
                                CategoryId = "D1"
                            }
                        ]
                    }
                    ]
                }
            });

        // Documents
        Mocker.GetMock<IProjectModificationsService>()
            .Setup(s => s.GetDocumentsForModification(
                modId,
                It.IsAny<ProjectOverviewDocumentSearchRequest>(),
                It.IsAny<int>(),
                It.IsAny<int>(),
                It.IsAny<string?>(),
                It.IsAny<string?>()))
            .ReturnsAsync(new ServiceResponse<ProjectOverviewDocumentResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    TotalCount = 1,
                    Documents = [new() { DocumentType = "TypeA" }]
                }
            });

        // ranking
        Mocker.GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationRanking(It.IsAny<RankingOfChangeRequest>()))
            .ReturnsAsync(new ServiceResponse<RankingOfChangeResponse>
            {
                StatusCode = HttpStatusCode.OK,
                Content = new()
                {
                    ModificationType = new() { Substantiality = "Non-Notifiable", Order = 1 },
                    Categorisation = new() { Category = "C", Order = 1 }
                }
            });

        Mocker.GetMock<IValidator<QuestionnaireViewModel>>()
            .Setup(v => v.ValidateAsync(It.IsAny<ValidationContext<QuestionnaireViewModel>>(), default))
            .ReturnsAsync(new ValidationResult());

        // Act
        var result = await Sut.ModificationDetails("PR1", "IRAS", "Short", modId, sponsorUserId, rtsId);

        // Assert
        var view = result.ShouldBeOfType<ViewResult>();
        var model = view.Model.ShouldBeOfType<ModificationDetailsViewModel>();

        model.SponsorOrganisationUserId.ShouldBe(sponsorUserId.ToString());
        model.RtsId.ShouldBe(rtsId);

        model.SponsorDetails.Count.ShouldBe(1);
        model.SponsorDetails[0].AnswerText.ShouldBe("SponsorAnswer");

        model.ProjectOverviewDocumentViewModel.Documents.Count().ShouldBe(1);
        model.ProjectOverviewDocumentViewModel.Pagination.AdditionalParameters["sponsorOrganisationUserId"]
            .ShouldBe(sponsorUserId.ToString());
    }
}