using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Rsp.IrasPortal.Application.Constants;
using Rsp.IrasPortal.Application.DTOs.CmsQuestionset;
using Rsp.IrasPortal.Application.DTOs.CmsQuestionset.Modifications;
using Rsp.IrasPortal.Web.Features.Modifications;
using Rsp.IrasPortal.Web.Models;

namespace Rsp.IrasPortal.UnitTests.Web.Features.Modifications;

public class ApplySelectionToAreaOfChangeTests : TestServiceBase<ModificationsController>
{
    [Theory, AutoData]
    public void ApplySelectionToAreaOfChange_ReturnsServiceError_WhenTempDataIsEmpty(string areaOfChangeId)
    {
        // Arrange
        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>());
        Sut.ControllerContext = new ControllerContext
        {
            HttpContext = new DefaultHttpContext()
        };

        // Act
        var result = Sut.ApplySelectionToAreaOfChange(areaOfChangeId);

        // Assert
        var serviceErrorResult = result.ShouldBeOfType<StatusCodeResult>();
        serviceErrorResult.StatusCode.ShouldBe((int)HttpStatusCode.BadRequest);
    }

    [Theory, AutoData]
    public void ApplySelectionToAreaOfChange_Redirects_WhenSelectedAreaNotFound(string areaOfChangeId)
    {
        // Arrange
        var tempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            [TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(new List<AreaOfChangeDto>
            {
                new AreaOfChangeDto { AutoGeneratedId = "different-id", OptionName = "Other Area" }
            })
        };

        Sut.TempData = tempData;

        // Act
        var result = Sut.ApplySelectionToAreaOfChange(areaOfChangeId);

        // Assert
        var redirectResult = result.ShouldBeOfType<RedirectToActionResult>();
        redirectResult.ActionName.ShouldBe("AreaOfChange");
    }

    [Fact]
    public void ApplySelectionToAreaOfChange_ReturnsView_WhenSelectedAreaExists()
    {
        // Arrange
        var selectedId = "area-123";
        var tempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            [TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(new List<AreaOfChangeDto>
            {
                new AreaOfChangeDto
                {
                    AutoGeneratedId = selectedId,
                    OptionName = "Test Area",
                    SpecificAreasOfChange = new List<AnswerModel>
                    {
                        new AnswerModel { AutoGeneratedId = "spec-1", OptionName = "Specific 1" },
                        new AnswerModel { AutoGeneratedId = "spec-2", OptionName = "Specific 2" }
                    }
                }
            })
        };

        Sut.TempData = tempData;

        // Act
        var result = Sut.ApplySelectionToAreaOfChange(selectedId);

        // Assert
        var viewResult = result.ShouldBeOfType<ViewResult>();
        var model = viewResult.Model.ShouldBeOfType<AreaOfChangeViewModel>();
        model.AreaOfChangeId.ShouldBe(selectedId);
        model.SpecificChangeOptions.Count().ShouldBe(2);
        model.SpecificChangeOptions.First().Text.ShouldBe("Specific 1");
    }
}