using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Rsp.Portal.Application.Constants;
using Rsp.Portal.Application.DTOs;
using Rsp.Portal.Application.DTOs.CmsQuestionset;
using Rsp.Portal.Application.DTOs.CmsQuestionset.Modifications;
using Rsp.Portal.Application.DTOs.Responses;
using Rsp.Portal.Web.Features.Modifications;

namespace Rsp.Portal.UnitTests.Web.Features.Modifications;

public class GetSpecificChangeByIdTests : TestServiceBase<ModificationsController>
{
    public GetSpecificChangeByIdTests()
    {
        var ctx = new DefaultHttpContext();
        Sut.ControllerContext = new ControllerContext { HttpContext = ctx };
        Sut.TempData = new TempDataDictionary(ctx, Mock.Of<ITempDataProvider>());
    }

    [Fact]
    public void GetSpecificChangesByAreaId_Should_Return_BadRequest_When_No_TempData()
    {
        // Act
        var result = Sut.GetSpecificChangesByAreaId("A1");

        // Assert
        result.ShouldBeOfType<StatusCodeResult>().StatusCode.ShouldBe(StatusCodes.Status400BadRequest);
    }

    [Fact]
    public void GetSpecificChangesByAreaId_Should_Return_Empty_List_When_Area_Not_Found()
    {
        // Arrange
        var areas = new List<AreaOfChangeDto>
        {
            new() { AutoGeneratedId = "A1", OptionName = "Area 1", SpecificAreasOfChange = [] }
        };
        Sut.TempData[TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(areas);

        // Act
        var result = Sut.GetSpecificChangesByAreaId("A2") as JsonResult;

        // Assert
        result.ShouldNotBeNull();
        var list = result.Value.ShouldBeOfType<List<SelectListItem>>();
        list.Count.ShouldBe(1); // only the default item
    }

    [Fact]
    public void GetSpecificChangesByAreaId_Should_Return_SpecificChanges()
    {
        // Arrange
        var areas = new List<AreaOfChangeDto>
        {
            new()
            {
                AutoGeneratedId = "A1",
                OptionName = "Area 1",
                SpecificAreasOfChange =
                [
                    new() { AutoGeneratedId = "S1", OptionName = "Spec 1" },
                    new() { AutoGeneratedId = "S2", OptionName = "Spec 2" }
                ]
            }
        };
        Sut.TempData[TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(areas);

        // Act
        var result = Sut.GetSpecificChangesByAreaId("A1") as JsonResult;

        // Assert
        result.ShouldNotBeNull();
        var list = result.Value.ShouldBeOfType<List<SelectListItem>>();
        list.Count.ShouldBe(3); // default + 2
        list[1].Value.ShouldBe("S1");
        list[2].Value.ShouldBe("S2");
    }

    [Fact]
    public void GetSpecificChangesByAreaId_ReturnsSpecificChanges_WhenValidAreaOfChangeId()
    {
        // Arrange
        var modificationResponse = new List<GetAreaOfChangesResponse>
        {
            new() {
                Id = "1",
                Name = "Test Area of Change",
                ModificationSpecificAreaOfChanges =
                [
                    new ModificationSpecificAreaOfChangeDto
                    {
                        Id = "1",
                        Name = "Specific Area 1",
                        JourneyType = "specific area 1",
                        ModificationAreaOfChangeId = 1
                    },
                    new ModificationSpecificAreaOfChangeDto
                    {
                        Id = "2",
                        Name = "Specific Area 2",
                        JourneyType = "specific area 2",
                        ModificationAreaOfChangeId = 1
                    }
                ]
            }
        };

        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            [TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(modificationResponse)
        };

        // Act
        var result = Sut.GetSpecificChangesByAreaId("1");

        // Assert
        var jsonResult = result.ShouldBeOfType<JsonResult>();
        var selectList = jsonResult.Value.ShouldBeOfType<List<SelectListItem>>();

        selectList.Count.ShouldBe(1);
        selectList[0].Text.ShouldBe("Select specific change");
    }

    [Fact]
    public void GetSpecificChangesByAreaId_ReturnsBadRequest_WhenSessionIsMissing()
    {
        // Arrange
        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>());

        // Act
        var result = Sut.GetSpecificChangesByAreaId("123");

        // Assert
        var badRequest = result.ShouldBeOfType<StatusCodeResult>();
        badRequest.StatusCode.ShouldBe(StatusCodes.Status400BadRequest);
    }

    [Fact]
    public void GetSpecificChangesByAreaId_WhenTempDataMissing_ReturnsBadRequest()
    {
        // Arrange
        // Arrange
        var areas = new List<AreaOfChangeDto>
        {
            new()
            {
                AutoGeneratedId = "A1",
                OptionName = "Area 1",
                SpecificAreasOfChange =
                [
                    new() { AutoGeneratedId = "S1", OptionName = "Spec 1" },
                    new() { AutoGeneratedId = "S2", OptionName = "Spec 2" }
                ]
            }
        };
        Sut.TempData[TempDataKeys.ProjectModification.AreaOfChanges] = JsonSerializer.Serialize(areas);

        // Act
        var result = Sut.GetSpecificChangesByAreaId(Guid.NewGuid().ToString());

        // Assert
        result.ShouldBeOfType<JsonResult>();
        var objectResult = (JsonResult)result;
        objectResult.ShouldNotBeNull();
    }

    [Fact]
    public void GetSpecificChangesByAreaId_ProjectHalt_ReturnsOnlyDefaultPlusProjectRestart()
    {
        // Arrange
        var (areas, selectedAreaId) = SampleAreas();

        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            { TempDataKeys.ProjectModification.AreaOfChanges, Serialize(areas) },
            { TempDataKeys.ProjectRecordStatus, ProjectRecordStatus.ProjectHalt }
        };

        // Act
        var result = Sut.GetSpecificChangesByAreaId(selectedAreaId);

        // Assert
        var list = ExtractJsonSelectList(result);

        list[0].Text.ShouldBe("Select specific change");
        list[0].Value.ShouldBe(Guid.Empty.ToString());

        list[1].Text.ShouldBe("Project restart following temporary halt");
        list[1].Value.ShouldNotBeNullOrEmpty();
    }

    [Fact]
    public void GetSpecificChangesByAreaId_ProjectHalt_MatchingIsCaseInsensitiveAndTrimmed()
    {
        // Arrange: introduce varying casing and whitespace
        var (areas, selectedAreaId) = SampleAreas();

        var target = areas
            .First(a => a.AutoGeneratedId == selectedAreaId)
            .SpecificAreasOfChange
            .First(sc => sc.OptionName.Equals("Project restart following temporary halt", StringComparison.OrdinalIgnoreCase));

        target.OptionName = "Project restart following temporary halt";

        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            { TempDataKeys.ProjectModification.AreaOfChanges, Serialize(areas) },
            { TempDataKeys.ProjectRecordStatus, ProjectRecordStatus.ProjectHalt }
        };

        // Act
        var result = Sut.GetSpecificChangesByAreaId(selectedAreaId);

        // Assert
        var list = ExtractJsonSelectList(result);

        list[1].Text.Trim().ShouldBe("Project restart following temporary halt");
    }

    [Fact]
    public void GetSpecificChangesByAreaId_NotProjectHalt_ReturnsAllSpecificItems()
    {
        // Arrange
        var (areas, selectedAreaId) = SampleAreas();

        Sut.TempData = new TempDataDictionary(new DefaultHttpContext(), Mock.Of<ITempDataProvider>())
        {
            { TempDataKeys.ProjectModification.AreaOfChanges, Serialize(areas) },
            { TempDataKeys.ProjectRecordStatus, ProjectRecordStatus.ProjectHalt }
        };

        // Act
        var result = Sut.GetSpecificChangesByAreaId(selectedAreaId);

        // Assert
        var list = ExtractJsonSelectList(result);

        // Expect: default select + all 3 specific items
        list[0].Text.ShouldBe("Select specific change");

        var texts = list.Skip(1).Select(i => i.Text).ToList();
        texts.ShouldBe(new[] {
                "Project restart following temporary halt",
        });
    }

    private (List<AreaOfChangeDto> Areas, string SelectedAreaId) SampleAreas()
    {
        var areaId = Guid.NewGuid().ToString();
        var areas = new List<AreaOfChangeDto>
            {
                new()
                {
                    AutoGeneratedId = areaId,
                    OptionName = "Stop or restart",
                    SpecificAreasOfChange = new List<AnswerModel>
                    {
                        new() { AutoGeneratedId = Guid.NewGuid().ToString(), OptionName = "Temporary halt to a project" },
                        new() { AutoGeneratedId = Guid.NewGuid().ToString(), OptionName = "Project restart following temporary halt" },
                        new() { AutoGeneratedId = Guid.NewGuid().ToString(), OptionName = "Other stop or restart of the project" },
                    }
                },
                new()
                {
                    AutoGeneratedId = Guid.NewGuid().ToString(),
                    OptionName = "Something else",
                    SpecificAreasOfChange = new List<AnswerModel>
                    {
                        new() { AutoGeneratedId = Guid.NewGuid().ToString(), OptionName = "Other A" },
                        new() { AutoGeneratedId = Guid.NewGuid().ToString(), OptionName = "Other B" }
                    }
                }
            };

        return (areas, areaId);
    }

    private static List<SelectListItem> ExtractJsonSelectList(IActionResult result)
    {
        result.ShouldBeOfType<JsonResult>();
        var json = (JsonResult)result;
        json.Value.ShouldNotBeNull();
        return ((IEnumerable<SelectListItem>)json.Value!).ToList();
    }

    private static string Serialize(object obj) =>
           JsonSerializer.Serialize(obj);
}