namespace Rsp.IrasPortal.Application.DTOs.CmsQuestionset;

public class AnswerModel
{
    public string? OptionName { get; set; }
    public string? Id { get; set; }
    public string? AutoGeneratedId { get; set; }
    public bool ShowApplicabilityQuestions { get; set; }
}