using Rsp.IrasPortal.Application.DTOs.Responses.CmsContent;

namespace Rsp.IrasPortal.Application.DTOs.CmsQuestionset;

public class SectionModel
{
    public string? SectionName { get; set; }

    /// <summary>
    /// Auto generated by the CMS
    /// </summary>
    public string Id { get; set; } = null!;

    /// <summary>
    /// Manually assigned by a CMS user
    /// </summary>
    public string? SectionId { get; set; }

    /// <summary>
    /// Category for the section, manually assigned by a CMS user
    /// </summary>
    public string? CategoryId { get; set; }

    /// <summary>
    /// Static view/action name to render/call
    /// </summary>
    public string? StaticViewName { get; set; }

    /// <summary>
    /// Indicates if this section is mandatory for the next section
    /// </summary>
    public bool IsMandatory { get; set; }

    public int Sequence { get; set; }

    /// <summary>
    /// Contains the questions in this section
    /// </summary>
    public IList<QuestionModel> Questions { get; set; } = [];

    /// <summary>
    /// Contains UI content components in this section
    /// </summary>
    public IList<ComponentContent> GuidanceComponents { get; set; } = [];
}