using System.Text.Json;
using Rsp.IrasPortal.Application.Constants;
using Rsp.IrasPortal.Application.DTOs.CmsQuestionset;
using Rsp.IrasPortal.Application.DTOs.Requests;
using Rsp.IrasPortal.Application.DTOs.Responses;
using Rsp.IrasPortal.Application.Services;
using static Rsp.IrasPortal.Application.Constants.TempDataKeys;

namespace Rsp.IrasPortal.Services;

public class ModificationRankingService
(
    ICmsQuestionsetService cmsQuestionsetService,
    IRespondentService respondentService,
    IProjectModificationsService projectModificationsService
) : IModificationRankingService
{
    public async Task UpdateChangeRanking(Guid modificationChangeId, string projectRecordId)
    {
        // Get the change to discover specific area
        var changeResp = await projectModificationsService.GetModificationChange(modificationChangeId);
        if (!changeResp.IsSuccessStatusCode || changeResp.Content is null)
            return;

        var change = changeResp.Content;

        // Get ShowApplicabilityQuestions from initial questions
        var initialResp = await cmsQuestionsetService.GetInitialModificationQuestions();
        if (!initialResp.IsSuccessStatusCode || initialResp.Content is null)
            return;

        var specificArea = initialResp.Content
            .AreasOfChange
            .SelectMany(a => a.SpecificAreasOfChange)
            .FirstOrDefault(s => s.AutoGeneratedId == change.SpecificAreaOfChange);

        var showApplicability = specificArea?.ShowApplicabilityQuestions ?? false;

        // Calculate
        var ranking = await CalculateChangeRanking
        (
            projectRecordId,
            change.SpecificAreaOfChange,
            showApplicability,
            modificationChangeId
        );

        // Persist minimal 3 fields (strings)
        var request = new ProjectModificationChangeRequest
        {
            Id = change.Id,
            ProjectModificationId = change.ProjectModificationId,
            AreaOfChange = change.AreaOfChange,
            SpecificAreaOfChange = change.SpecificAreaOfChange,
            Status = change.Status,
            CreatedBy = change.CreatedBy,
            UpdatedBy = change.UpdatedBy,
            ModificationType = ranking.ModificationType?.Substantiality ?? Ranking.NotAvailable,
            Category = ranking.Categorisation?.Category ?? Ranking.NotAvailable,
            ReviewType = ranking.ReviewType ?? Ranking.NotAvailable
        };

        await projectModificationsService.UpdateModificationChange(request);

        // old code
        // Get the ranking of change. The change is already calculated in the Ranking of Change component
        // and saved in TempData.
        var rankingOfChange = TempData[ProjectModificationChange.RankingOfChange] as string;

        if (!string.IsNullOrWhiteSpace(rankingOfChange))
        {
            var (_, projectModificationChangeId) = CheckModification();

            // get the current modification change in progress
            var modificationChange = await projectModificationsService.GetModificationChange(projectModificationChangeId);

            var rankingOfChangeModel = JsonSerializer.Deserialize<RankingOfChangeViewModel>(rankingOfChange);

            // adapt the modification change to request model
            var modificationChangeRequest = modificationChange.Content!.Adapt<ProjectModificationChangeRequest>();

            modificationChangeRequest.ModificationType = rankingOfChangeModel!.ModificationType;
            modificationChangeRequest.Category = rankingOfChangeModel.Category;
            modificationChangeRequest.ReviewType = rankingOfChangeModel.ReviewType;

            await projectModificationsService.UpdateModificationChange(modificationChangeRequest);
        }
    }

    public async Task UpdateOverallRanking(Guid projectModificationId, string projectRecordId)
    {
        // Modification + changes
        var modResp = await projectModificationsService.GetModification(projectModificationId);
        if (!modResp.IsSuccessStatusCode || modResp.Content is null)
            return;

        var changesResp = await projectModificationsService.GetModificationChanges(projectModificationId);
        if (!changesResp.IsSuccessStatusCode || changesResp.Content is null)
            return;

        var initialResp = await cmsQuestionsetService.GetInitialModificationQuestions();
        if (!initialResp.IsSuccessStatusCode || initialResp.Content is null)
            return;

        var initial = initialResp.Content;
        var mod = modResp.Content;

        // Rebuild the full update request and recompute per-change ranking
        var modRequest = new ProjectModificationRequest
        {
            Id = mod.Id,
            ProjectRecordId = mod.ProjectRecordId,
            Status = mod.Status,
            CreatedBy = mod.CreatedBy,
            UpdatedBy = mod.UpdatedBy,
            // ensure list exists
            ProjectModificationChanges = new List<ProjectModificationChangeRequest>()
        };

        // For each change: recompute and attach enriched change request
        foreach (var change in changesResp.Content.OrderByDescending(c => c.CreatedDate))
        {
            if (change.AreaOfChange == Guid.Empty.ToString() || change.SpecificAreaOfChange == Guid.Empty.ToString())
                continue;

            var area = initial.AreasOfChange.Find(a => a.AutoGeneratedId == change.AreaOfChange);
            var specific = area?.SpecificAreasOfChange.Find(s => s.AutoGeneratedId == change.SpecificAreaOfChange);
            if (specific is null) continue;

            var ranking = await CalculateChangeRanking
            (
                mod.ProjectRecordId,
                specific.AutoGeneratedId!,
                specific.ShowApplicabilityQuestions,
                change.Id
            );

            // Derive persisted strings and the (Category, Order) and (Substantiality, Order) pairs
            var modificationType = ranking.ModificationType?.Substantiality ?? Ranking.NotAvailable;

            var category =
                string.Equals(modificationType, Ranking.ModificationTypes.NonNotifiable, StringComparison.OrdinalIgnoreCase) ?
                Ranking.CategoryTypes.NA :
                ranking.Categorisation?.Category ?? Ranking.NotAvailable;

            var changeRequest = new ProjectModificationChangeRequest
            {
                Id = change.Id,
                ProjectModificationId = change.ProjectModificationId,
                AreaOfChange = change.AreaOfChange,
                SpecificAreaOfChange = change.SpecificAreaOfChange,
                Status = change.Status,
                CreatedBy = change.CreatedBy,
                UpdatedBy = change.UpdatedBy,
                ModificationType = modificationType,
                Category = category,
                ReviewType = ranking.ReviewType ?? Ranking.NotAvailable,
                ModificationSubstantiality = (modificationType, ranking.ModificationType?.Order ?? 0),
                Categorisation = (
                    category,
                    category == Ranking.CategoryTypes.NA ? 6 : (ranking.Categorisation?.Order ?? 0)
                )
            };

            modRequest.ProjectModificationChanges.Add(changeRequest);
        }

        // Let backend or shared rule compute overall ranking if available,
        // otherwise this request already contains per-change ranking to base it on.
        // If you have a shared aggregation method on the API, omit client-side aggregation.

        await projectModificationsService.UpdateModification(modRequest);
    }

    public async Task<RankingOfChangeResponse> CalculateChangeRanking
    (
        string projectRecordId,
        string specificAreaOfChangeId,
        bool showApplicabilityQuestions,
        Guid modificationChangeId
    )
    {
        // Journey for specific area
        var journeyResp = await cmsQuestionsetService.GetModificationsJourney(specificAreaOfChangeId);
        if (!journeyResp.IsSuccessStatusCode || journeyResp.Content is null)
            return new RankingOfChangeResponse();

        // Answers for the change
        var answersResp = await respondentService.GetModificationChangeAnswers(modificationChangeId, projectRecordId);
        var answers = answersResp.IsSuccessStatusCode ? (answersResp.Content ?? []) : [];

        // If applicability is false, source NHS/HSC from Project Record (IQA0004) — uses answer id constant
        string nhsOrHscOrganisations = string.Empty;
        if (!showApplicabilityQuestions)
        {
            var projectRecordAnswersResp = await respondentService.GetRespondentAnswers(projectRecordId, QuestionCategories.ProjectRecord);
            var prAnswers = projectRecordAnswersResp.Content ?? [];
            var ans = prAnswers.FirstOrDefault(a => a.QuestionId == QuestionIds.NhsOrHscOrganisations);
            nhsOrHscOrganisations = ans?.SelectedOption switch
            {
                var x when x == QuestionAnswersOptionsIds.Yes => "Yes",
                _ => "No"
            };
        }

        // Build the RankingOfChangeRequest from CMS metadata + respondent answers (no ViewModels)
        var rankingReq = BuildRankingOfChangeRequest(journeyResp.Content, answers, showApplicabilityQuestions, nhsOrHscOrganisations);

        var rankingResp = await cmsQuestionsetService.GetModificationRanking(rankingReq);
        return rankingResp.Content ?? new RankingOfChangeResponse();
    }

    private static RankingOfChangeRequest BuildRankingOfChangeRequest
    (
        CmsQuestionSetResponse cms,
        IEnumerable<RespondentAnswerDto> respondentAnswers,
        bool applicability,
        string nhsOrHscOrganisations
    )
    {
        // Flatten questions for lookup by QuestionId
        var questions = cms.Sections.SelectMany(s => s.Questions).ToList();

        QuestionModel? nhsInvolvementQuestion = null;

        if (nhsOrHscOrganisations == "Yes")
        {
            // Force NHS involvement
            nhsInvolvementQuestion = new QuestionModel { QuestionId = "forced" };
        }
        else
        {
            nhsInvolvementQuestion = questions
                .SingleOrDefault(q =>
                    q.NhsInvolvment != null &&
                    IsAnswerTextSelected(respondentAnswers, q));
        }

        var nonNhsQuestion = questions
            .SingleOrDefault(q =>
                q.NonNhsInvolvment != null &&
                IsAnswerTextSelected(respondentAnswers, q));

        var orgsAffectedQuestion = questions.SingleOrDefault(q => q.AffectedOrganisations);
        var additionalResourcesQuestion = questions.SingleOrDefault(q => q.RequireAdditionalResources);

        var isNhsInvolved = nhsInvolvementQuestion is not null;

        var nhsOrganisationsAffected = string.Empty;
        if (nhsOrHscOrganisations == "Yes")
        {
            nhsOrganisationsAffected = "All";
        }
        else
        {
            nhsOrganisationsAffected = GetSelectedAnswerText(respondentAnswers, orgsAffectedQuestion) ?? string.Empty;
        }

        var nhsResourceImplications = string.Equals(
            GetSelectedAnswerText(respondentAnswers, additionalResourcesQuestion) ?? string.Empty,
            "Yes",
            StringComparison.OrdinalIgnoreCase);

        return new RankingOfChangeRequest
        {
            SpecificAreaOfChangeId = questions.FirstOrDefault()?.CategoryId is null ?
                string.Empty
                : "", // SpecificAreaOfChangeId is passed by caller; set below
            Applicability = applicability ? "Yes" : "No",
            IsNHSInvolved = isNhsInvolved,
            IsNonNHSInvolved = nonNhsQuestion is not null,
            NhsOrganisationsAffected = nhsOrganisationsAffected,
            NhsResourceImplicaitons = nhsResourceImplications
        };
    }

    private static bool IsAnswerTextSelected(IEnumerable<RespondentAnswerDto> answers, QuestionModel q)
    {
        var a = answers.FirstOrDefault(x => x.QuestionId == q.QuestionId);
        if (a == null) return false;

        // Single selection? (SelectedOption matches AnswerId; compare its OptionName to q.NhsInvolvment/NonNhsInvolvment)
        if (!string.IsNullOrWhiteSpace(a.SelectedOption) && q.Answers?.Any() == true)
        {
            var selectedOpt = q.Answers.FirstOrDefault(opt => opt.Id == a.SelectedOption);
            var selectedText = selectedOpt?.OptionName ?? a.SelectedOption; // fallback
            return string.Equals(selectedText, q.NhsInvolvment ?? q.NonNhsInvolvment, StringComparison.OrdinalIgnoreCase);
        }

        // Multiple answers case
        if (a.Answers?.Count > 0 && q.Answers?.Any() == true)
        {
            var selectedTexts = q.Answers.Where(opt => a.Answers.Contains(opt.Id)).Select(opt => opt.OptionName);
            var needle = q.NhsInvolvment ?? q.NonNhsInvolvment;
            return selectedTexts.Any(t => string.Equals(t, needle, StringComparison.OrdinalIgnoreCase));
        }

        // Fallback to free text
        if (!string.IsNullOrWhiteSpace(a.AnswerText))
        {
            return string.Equals(a.AnswerText, q.NhsInvolvment ?? q.NonNhsInvolvment, StringComparison.OrdinalIgnoreCase);
        }

        return false;
    }

    private static string? GetSelectedAnswerText(IEnumerable<RespondentAnswerDto> answers, QuestionModel? q)
    {
        if (q is null) return null;

        var a = answers.FirstOrDefault(x => x.QuestionId == q.QuestionId);
        if (a == null) return null;

        if (!string.IsNullOrWhiteSpace(a.SelectedOption) && q.Answers?.Any() == true)
        {
            return q.Answers.FirstOrDefault(opt => opt.Id == a.SelectedOption)?.OptionName;
        }

        if (a.Answers?.Count > 0 && q.Answers?.Any() == true)
        {
            // return first or join as needed; the Ranking request expects a single text for AffectedOrganisations
            return q.Answers.FirstOrDefault(opt => a.Answers.Contains(opt.Id))?.OptionName;
        }

        return a.AnswerText;
    }
}