using Rsp.IrasPortal.Application.Constants;
using Rsp.IrasPortal.Application.DTOs.CmsQuestionset;
using Rsp.IrasPortal.Application.DTOs.CmsQuestionset.Modifications;
using Rsp.IrasPortal.Application.DTOs.Requests;
using Rsp.IrasPortal.Application.DTOs.Responses;
using Rsp.IrasPortal.Application.Responses;
using Rsp.IrasPortal.Application.Services;
using Rsp.IrasPortal.Services;

namespace Rsp.IrasPortal.UnitTests.Services.ModificationRankingServiceTests;

public class UpdateChangeRankingTests : TestServiceBase<ModificationRankingService>
{
    [Fact]
    public async Task Does_Nothing_When_ModificationChange_Not_Found()
    {
        // Arrange - GetModificationChange fails
        var changeId = Guid.NewGuid();
        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChange(changeId))
            .ReturnsAsync(new ServiceResponse<ProjectModificationChangeResponse> { StatusCode = System.Net.HttpStatusCode.NotFound });

        // Act
        await Sut.UpdateChangeRanking(changeId, "PR1");

        // Assert - no update call invoked
        Mocker
            .GetMock<IProjectModificationsService>()
            .Verify(s => s.UpdateModificationChange(It.IsAny<ProjectModificationChangeRequest>()), Times.Never);
    }

    [Fact]
    public async Task Updates_Change_With_Computed_Ranking()
    {
        // Arrange
        var changeId = Guid.NewGuid();
        var modificationChange = new ProjectModificationChangeResponse { Id = changeId, SpecificAreaOfChange = "SA1" };
        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChange(changeId))
            .ReturnsAsync(new ServiceResponse<ProjectModificationChangeResponse> { StatusCode = HttpStatusCode.OK, Content = modificationChange });

        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetInitialModificationQuestions())
            .ReturnsAsync(new ServiceResponse<StartingQuestionsDto> { StatusCode = HttpStatusCode.OK, Content = new StartingQuestionsDto { AreasOfChange = [new AreaOfChangeDto { SpecificAreasOfChange = [new AnswerModel { AutoGeneratedId = "SA1", ShowApplicabilityQuestions = true }] }] } });

        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationsJourney("SA1"))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse> { StatusCode = HttpStatusCode.OK, Content = new CmsQuestionSetResponse { Sections = [new SectionModel { Questions = [] }] } });

        Mocker
            .GetMock<IRespondentService>()
            .Setup(s => s.GetModificationChangeAnswers(changeId, "PR1"))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>> { StatusCode = HttpStatusCode.OK, Content = [] });

        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationRanking(It.IsAny<RankingOfChangeRequest>()))
            .ReturnsAsync(new ServiceResponse<RankingOfChangeResponse> { StatusCode = HttpStatusCode.OK, Content = new RankingOfChangeResponse { ModificationType = new() { Substantiality = Ranking.ModificationTypes.NonNotifiable, Order = 99 }, Categorisation = new() { Category = Ranking.CategoryTypes.A, Order = 1 }, ReviewType = Ranking.ReviewTypes.NoReviewRequired } });

        ProjectModificationChangeRequest? captured = null;
        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.UpdateModificationChange(It.IsAny<ProjectModificationChangeRequest>()))
            .Callback<ProjectModificationChangeRequest>(r => captured = r)
            .ReturnsAsync(new ServiceResponse { StatusCode = HttpStatusCode.OK });

        // Act
        await Sut.UpdateChangeRanking(changeId, "PR1");

        // Assert
        captured.ShouldNotBeNull();
        captured.ModificationType.ShouldBe(Ranking.ModificationTypes.NonNotifiable);
        captured.Category.ShouldBe(Ranking.CategoryTypes.NA); // forced N/A when Non-Notifiable
        captured.ReviewType.ShouldBe(Ranking.ReviewTypes.NoReviewRequired);
    }
}