using Rsp.Portal.Application.Constants;
using Rsp.Portal.Application.DTOs.CmsQuestionset;
using Rsp.Portal.Application.DTOs.CmsQuestionset.Modifications;
using Rsp.Portal.Application.DTOs.Requests;
using Rsp.Portal.Application.DTOs.Responses;
using Rsp.Portal.Application.Responses;
using Rsp.Portal.Application.Services;
using Rsp.Portal.Services;

namespace Rsp.Portal.UnitTests.Services.ModificationRankingServiceTests;

public class UpdateOverallRankingTests : TestServiceBase<ModificationRankingService>
{
    [Fact]
    public async Task Does_Nothing_When_Modification_Not_Found()
    {
        var modId = Guid.NewGuid();
        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModification(It.IsAny<string>(), It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<ProjectModificationResponse> { StatusCode = HttpStatusCode.NotFound });

        await Sut.UpdateOverallRanking(modId, "PR1");

        Mocker
            .GetMock<IProjectModificationsService>()
            .Verify(s => s.UpdateModification(It.IsAny<ProjectModificationRequest>()), Times.Never);
    }

    [Fact]
    public async Task Aggregates_Change_Rankings_To_Overall_Modification()
    {
        var modId = Guid.NewGuid();
        var change1 = new ProjectModificationChangeResponse { Id = Guid.NewGuid(), SpecificAreaOfChange = "SA1", AreaOfChange = "A1" };
        var change2 = new ProjectModificationChangeResponse { Id = Guid.NewGuid(), SpecificAreaOfChange = "SA2", AreaOfChange = "A1" };

        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModification(It.IsAny<string>(), It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<ProjectModificationResponse> { StatusCode = HttpStatusCode.OK, Content = new ProjectModificationResponse { Id = modId } });

        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.GetModificationChanges(It.IsAny<string>(), It.IsAny<Guid>()))
            .ReturnsAsync(new ServiceResponse<IEnumerable<ProjectModificationChangeResponse>> { StatusCode = HttpStatusCode.OK, Content = new[] { change1, change2 } });

        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetInitialModificationQuestions())
            .ReturnsAsync(new ServiceResponse<StartingQuestionsDto> { StatusCode = HttpStatusCode.OK, Content = new StartingQuestionsDto { AreasOfChange = [new AreaOfChangeDto { AutoGeneratedId = "A1", SpecificAreasOfChange = [new AnswerModel { AutoGeneratedId = "SA1", ShowApplicabilityQuestions = true }, new AnswerModel { AutoGeneratedId = "SA2", ShowApplicabilityQuestions = true }] }] } });

        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationsJourney(It.IsAny<string>()))
            .ReturnsAsync(new ServiceResponse<CmsQuestionSetResponse> { StatusCode = HttpStatusCode.OK, Content = new CmsQuestionSetResponse { Sections = [new SectionModel { Questions = [] }] } });

        Mocker
            .GetMock<IRespondentService>()
            .Setup(s => s.GetModificationChangeAnswers(It.IsAny<Guid>(), It.IsAny<string>()))
            .ReturnsAsync(new ServiceResponse<IEnumerable<RespondentAnswerDto>> { StatusCode = HttpStatusCode.OK, Content = [] });

        var sequence = 0;
        Mocker
            .GetMock<ICmsQuestionsetService>()
            .Setup(s => s.GetModificationRanking(It.IsAny<RankingOfChangeRequest>()))
            .ReturnsAsync(() =>
                {
                    sequence++;
                    return new ServiceResponse<RankingOfChangeResponse>
                    {
                        StatusCode = HttpStatusCode.OK,
                        Content = new RankingOfChangeResponse
                        {
                            ModificationType = new() { Substantiality = sequence == 1 ? Ranking.ModificationTypes.MinorModification : Ranking.ModificationTypes.Substantial, Order = sequence == 1 ? 2 : 1 },
                            Categorisation = new() { Category = sequence == 1 ? Ranking.CategoryTypes.B : Ranking.CategoryTypes.C, Order = sequence == 1 ? 3 : 2 },
                            ReviewType = sequence == 1 ? Ranking.ReviewTypes.NoReviewRequired : Ranking.ReviewTypes.ReviewRequired
                        }
                    };
                });

        ProjectModificationRequest? captured = null;
        Mocker
            .GetMock<IProjectModificationsService>()
            .Setup(s => s.UpdateModification(It.IsAny<ProjectModificationRequest>()))
            .Callback<ProjectModificationRequest>(r => captured = r)
            .ReturnsAsync(new ServiceResponse { StatusCode = HttpStatusCode.OK });

        await Sut.UpdateOverallRanking(modId, "PR1");

        captured.ShouldNotBeNull();
        captured.ProjectModificationChanges.Count.ShouldBe(2);
        captured.ModificationType.ShouldBe(Ranking.ModificationTypes.Substantial);
        captured.Category.ShouldBe(Ranking.CategoryTypes.BC);
        captured.ReviewType.ShouldBe(Ranking.ReviewTypes.ReviewRequired);
    }
}